Add support for typing.Annotated
ets-labs/python-dependency-injector pull request #721
Opened 2023-07-09 09:33 UTC by maintain0404

Resolve #693.

This PR supports using typing.Annotated instead of parameter defaults when defining markers.

2023-12-06 21:34 UTC, TimNekk commented
This addition is really nice! I hope it will be merged

2024-03-07 03:50 UTC, maintain0404 commented
@4c0n If this commit is used, rather than the copied code, you're welcome.

2024-03-28 14:03 UTC, abdok96 commented
@maintain0404 sorry for submitting a review by mistake. I was just checking the changes.

I hope your PR get merged soon! However I noticed that your implementation don't support [injections into modules and class attributes](https://python-dependency-injector.ets-labs.org/wiring.html#making-injections-into-modules-and-class-attributes). 

The following code should add support for that:

```python
def _get_members_and_annotated(obj: Any) -> list[tuple[str, Any]]:
    members = inspect.getmembers(obj)
    for ann_name, annotation in inspect.get_annotations(obj).items():
        if get_origin(annotation) is Annotated:
            member = get_args(annotation)[1]
            members.append((ann_name, member))
    return members
```

And then in `wire` you use that function instead of `inspect.getmembers`:

```python
def wire(  # noqa: C901
    container: Container,
    *,
    modules: Optional[Iterable[ModuleType]] = None,
    packages: Optional[Iterable[ModuleType]] = None,
) -> None:
    ....
    for module in modules:
        for member_name, member in _get_members_with_annotated(module):
             ...
             elif inspect.isclass(member):
                cls = member
                try:
                    cls_members = _get_members_with_annotated(cls)
                except Exception:  # noqa
                    # Hotfix, see: https://github.com/ets-labs/python-dependency-injector/issues/441
                    continue
```

2024-07-30 00:57 UTC, JobaDiniz commented
Hey, is this _dead_? Why didn't this get merged?

2024-10-17 14:42 UTC, wadinj commented
Hello,

Is there any plan to getting this merge?

2024-11-19 19:13 UTC, stounfo commented
Hey @rmk135,
Any chance that this pr will be considered soon?
Many thanks for considering this request.

2025-01-11 12:31 UTC, ELC commented
Any updates on this? @ZipFile  @rmk135

2025-01-12 13:17 UTC, ZipFile requested changes
Looks more or less fine, run `black` against new code and it is good to go.

2025-01-18 15:17 UTC, maintain0404 commented
@ZipFile I can't find black config and version. Is it good to run with latest version and default config?

2025-01-20 15:10 UTC, ZipFile approved these changes

2025-01-20 15:36 UTC, rmk135 approved these changes

2025-01-20 15:37 UTC, merged

2025-05-21 20:15 UTC, rmk135 commented
This comment: https://github.com/ets-labs/python-dependency-injector/pull/721#issuecomment-2025263718

has been addressed in this PR: https://github.com/ets-labs/python-dependency-injector/pull/889

@abdok96 thank you for bringing this up.

2025-05-21 20:38 UTC, abdok96 commented
> This comment: https://github.com/ets-labs/python-dependency-injector/pull/721#issuecomment-2025263718
> 
> 
> 
> has been addressed in this PR: https://github.com/ets-labs/python-dependency-injector/pull/889
> 
> 
> 
> @abdok96 thank you for bringing this up.

Seems great! Thanks 🚀