fix: type propogation through provided
ets-labs/python-dependency-injector pull request #733
Opened 2023-08-03 00:32 UTC by philipbjorge

Addresses https://github.com/ets-labs/python-dependency-injector/issues/731

2025-01-06 14:58 UTC, jonathangreen commented
@rmk135 Any chance that this type fix could be merged as well?

2025-01-07 00:28 UTC, rmk135 commented
Thank you for the contribution @philipbjorge .

@ZipFile can you please review this PR when you have a moment?

2025-01-07 00:32 UTC, rmk135 commented on tests/typing/callable.py
> +provided5: Animal = provider5.provided
This test is not exactly correct. The attribute ``provider5.provided`` returns a provider, not an object of ``Animal``. I can't recall why it was important, but the current change will introduce a functional change in the typing approach.

To make a correct typing test with the ``.provided`` attribute we would need to do something like that:

```python
provided5: Animal = provider5.provided()
```

At least, that would be what the library actually does.

2025-01-07 17:48 UTC, philipbjorge commented
I don't have capacity to address any feedback here and no longer work at the company using this library -- But I've reached out to my previous teammates to see if they can carry the torch :)

Thanks for reviewing! Excited to see this project waking back up!

2025-01-07 20:31 UTC, GonzaGonza commented on tests/typing/callable.py
> +provided5: Animal = provider5.provided
@rmk135 updated the tests with `.provided()`

cc @philipbjorge thanks for flagging

2025-01-07 20:57 UTC, ZipFile requested changes

2025-01-07 20:57 UTC, ZipFile commented on src/dependency_injector/providers.pyi
> +    def provided(self) -> T: ...
```suggestion
    def provided(self) -> ProvidedInstance[T]: ...
```

2025-01-07 20:57 UTC, ZipFile commented on tests/typing/callable.py
> +provided5: Animal = provider5.provided()
If you run `mypy` against this code you'll get an error `tests/typing/callable.py:37: error: "Animal" not callable  [operator]`.

2025-01-07 20:57 UTC, ZipFile commented on tests/typing/callable.py
> -method_caller: providers.MethodCaller = provider5.provided.method.call(123, arg=324)
I think we should not remove this, since `provided` attribute is in fact `ProvidedInstance`:
https://github.com/ets-labs/python-dependency-injector/blob/46646b1acfd833eeb55075651af9a13fcb4762ef/src/dependency_injector/providers.pyx#L431-L434

2025-01-07 23:42 UTC, GonzaGonza commented on tests/typing/callable.py
> -method_caller: providers.MethodCaller = provider5.provided.method.call(123, arg=324)
@ZipFile I looked into this and I think you are right, I reintroduced the removed tests.

2025-01-08 11:21 UTC, ZipFile approved these changes
LGTM

2025-01-08 11:31 UTC, merged